FROM python:3.9-alpine3.13

WORKDIR /app/

ENV PYTHONPATH=/app \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  INSTALL_DEV=true

RUN apk add --no-cache --virtual .build-deps gcc \
        libc-dev make build-base openssl-dev \
        libffi-dev libxml2-dev libxslt-dev postgresql-dev \
        musl-dev cargo jpeg-dev zlib-dev libjpeg \
      && apk add netcat-openbsd curl postgresql-client build-base\
      && pip install -U setuptools pip

# RUN apk add netcat-openbsd curl

ADD requirements.txt .
RUN pip install -r requirements.txt

# Set Timezone
RUN apk add tzdata
ENV TZ=Asia/Jakarta

# Copy folder app
COPY ./app /app

COPY ./start.sh /start.sh
RUN chmod +x /start.sh

COPY ./gunicorn_conf.py /gunicorn_conf.py

COPY ./start-reload.sh /start-reload.sh
RUN chmod +x /start-reload.sh

EXPOSE 80

CMD ["/start.sh"]
